/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.richard.event.processor.java-application-conventions")
}

dependencies {
//    implementation("org.apache.commons:commons-text")
    implementation(project(":annotations"))
    annotationProcessor(project(":annotation-processor"))
}

application {
    // Define the main class for the application.
    mainClass.set("io.richard.event.processor.app.App")
}
