/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.richard.event.processor.java-application-conventions")
    id("groovy")
    id("com.github.johnrengelman.shadow") version "7.1.2"
    id("io.micronaut.application") version "3.5.1"
}

dependencies {
    implementation("org.slf4j:slf4j-api")
    implementation("org.slf4j:slf4j-simple")

    implementation(project(":annotations"))
    implementation(project(":micronaut-proxy-provider"))
    annotationProcessor(project(":annotation-processor"))

    implementation("io.micronaut:micronaut-jackson-databind")
    implementation("io.micronaut.picocli:micronaut-picocli")
    implementation("jakarta.annotation:jakarta.annotation-api")
    runtimeOnly("ch.qos.logback:logback-classic")
    implementation("io.micronaut:micronaut-validation")

    testImplementation("io.micronaut:micronaut-http-client")
//    implementation("jakarta.inject:jakarta.inject-api:2.0.1")
}

application {
    // Define the main class for the application.
    mainClass.set("io.richard.event.processor.app.App")
}

java {
    sourceCompatibility = JavaVersion.toVersion("19")
    targetCompatibility = JavaVersion.toVersion("19")
}

micronaut {
    testRuntime("spock2")
    processing {
        incremental(true)
        annotations("io.richard.event.processor.app.*")
    }
}
