/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.richard.event.processor.app;

public class App {
    public static void main(String[] args) {
        System.out.println("App is running");
    }
}
