/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.richard.event.processor.app;

import io.richard.event.processor.EventRecord;
import io.richard.event.processor.ProcessorHandlerInfo;
import io.richard.event.processor.ProductCreatedEventProcessorHandlerInfoImpl;
import java.util.UUID;

public class App {

    public static void main(String[] args) {
        ApplicationContext applicationContext = new ApplicationContext();
        applicationContext.put(new ProductCreatedKafkaEventProcessor());
        DependencyInjectionAdapter dependencyInjectionAdapter = new MicronautDependencyInjectionAdapter(
            applicationContext);
        ProcessorGroup processorGroup = new ProcessorGroup(dependencyInjectionAdapter);
        processorGroup.register(ProductCreatedEvent.class, new ProductCreatedEventProcessorHandlerInfoImpl());
//        System.out.println("App is running");
        processorGroup.process(new EventRecord<>(new ProductCreatedEvent(UUID.randomUUID(),
            "Argon M.2"), UUID.randomUUID(), "partition-key-2"));
    }
}
