/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.richard.event.processor.java-library-conventions")
}

dependencies {
    implementation(project(":annotations"))
    annotationProcessor("com.google.auto.service:auto-service:1.0")
    compileOnly("com.google.auto.service:auto-service:1.0")
}
